export { default as Account } from './AccountPage'
export { default as Dashboard } from './DashboardPage'
export { default as Icon } from './IconPage'
// export { default as NotFound } from './NotFoundPage'
export { default as Finance } from './FinancePage'
export { default as Setting } from './SettingPage'

export { default as Typography } from './TypographyPage'
export { default as Profile } from './ProfilePage'
export { default as First } from './FirstPage'
